### ISSUE TITLE
NACC ERROR: invalid container element id

### ISSUE THREAD

**Issue by fsrnadmin** [bmlt-enabled/nacc#12]
NACC ERROR: invalid container element id popup error occurs on freestatena.org, with OK button ...
after deactivating the plugin, error goes away

**Comment by pjaudiomv** [comment]
What version of Wordpress are you on and what's your short code look like

**Comment by pjaudiomv** [comment]
Just released new version [4.0.1](https://github.com/bmlt-enabled/nacc/tree/4.0.1) that should fix this
